export const SET_TICKET_AUTOMATION_RULE_UI_FLAG =
  'SET_TICKET_AUTOMATION_RULE_UI_FLAG';
export const SET_TICKET_AUTOMATION_RULES = 'SET_TICKET_AUTOMATION_RULES';
export const ADD_TICKET_AUTOMATION_RULE = 'ADD_TICKET_AUTOMATION_RULE';
export const EDIT_TICKET_AUTOMATION_RULE = 'EDIT_TICKET_AUTOMATION_RULE';
export const DELETE_TICKET_AUTOMATION_RULE = 'DELETE_TICKET_AUTOMATION_RULE';
