json.id resource.id
json.account_id resource.account_id
json.name resource.name
json.description resource.description
json.event_name resource.event_name
json.active resource.active
json.conditions resource.conditions
json.actions resource.actions
json.created_at resource.created_at
json.updated_at resource.updated_at
