export const SET_TICKET_STATUS_UI_FLAG = 'SET_TICKET_STATUS_UI_FLAG';
export const SET_TICKET_STATUSES = 'SET_TICKET_STATUSES';
export const ADD_TICKET_STATUS = 'ADD_TICKET_STATUS';
export const EDIT_TICKET_STATUS = 'EDIT_TICKET_STATUS';
export const DELETE_TICKET_STATUS = 'DELETE_TICKET_STATUS';
